### PR TITLE
module: add :editor meow

### PR DESCRIPTION
**Pull request by VitalyAnkh**
Add an `editor/meow` module, integrate [meow](https://github.com/meow-edit/meow) into Doom

### CODE REVIEW

**Comment by hlissner** [comment]
I'm not currently accepting new editing paradigm modules in Doom so I must turn this down, but I will be opening up a repository for community-developed modules in https://github.com/doomemacs/contrib-modules (not public yet) some time in the next few months (and changing how users can manage their module sources from their `doom!` block). I'll accept this module there, when it is available.

I'll keep this PR open until that happens.

**Comment by Not-Leader** [comment]
if you do add the meow module, [please use this one](https://github.com/Not-Leader/doom-meow)

**Comment by bdarcus** [comment]
> if you do add the meow module, [please use this one](https://github.com/Not-Leader/doom-meow)

What's the difference?

In any case, +1 on a meow contrib module.

**Comment by iyefrat** [comment]
@bdarcus 
That repo is a standalone module that can be easily imported to your private doom config (and eventually be moved to `contrib-modules`). To use this PR you'd have to live on an alternate doom git branch.

**Comment by ksqsf** [comment]
Hey, any progress on this?

**Comment by jgarte** [comment]
TIL:

https://github.com/meow-edit/doom-meow

https://toys.whereis.みんな/symbols?search=feature-emacs-meow

**Comment by VitalyAnkh** [comment]
For the time being, I recommend [this doom module for meow](https://github.com/45mg/doom-meow-module).

**Comment by not-leader** [comment]
because i was the maintainer lol


________________________________

**Comment by VitalyAnkh** [comment]
> why that one over doom-meow?

The original author of doom-meow (@not-leader) is not using doom any more and not maintainging doom-meow. I'm using [my own meow configuration for integration with doom](https://github.com/VitalyAnkh/doom/blob/vr/config.org#meow), which is opinionated and not suitable for general community module. https://github.com/45mg/doom-meow-module is clean and modular, and I have requested to include it in meow-edit organization: https://github.com/45mg/doom-meow-module/issues/1. If the author agreed, we will have an active maintainer and a place to improve the module together.

I have seen some PRs to doom-meow but I haven't got enought time (and interest :face_with_diagonal_mouth:) to review them. But if the author of https://github.com/45mg/doom-meow-modul doesn't repond in time(maybe one or two weeks), I plan to continue improving doom-meow.

**Comment by devdumpling** [comment]
> > why that one over doom-meow?
> 
> The original author of doom-meow (@not-leader) is not using doom any more and not maintainging doom-meow. I'm using [my own meow configuration for integration with doom](https://github.com/VitalyAnkh/doom/blob/vr/config.org#meow), which is opinionated and not suitable for general community module. https://github.com/45mg/doom-meow-module is clean and modular, and I have requested to include it in meow-edit organization: [45mg/doom-meow-module#1](https://github.com/45mg/doom-meow-module/issues/1). If the author agreed, we will have an active maintainer and a place to improve the module together.
> 
> I have seen some PRs to doom-meow but I haven't got enought time (and interest 🫤) to review them. But if the author of https://github.com/45mg/doom-meow-modul doesn't repond in time(maybe one or two weeks), I plan to continue improving doom-meow.

Thanks for the rundown--exactly the context I was looking for. I'm running with the 45mg doom-meow-module for now and will try to wrap my head around that. Once I have some idea what I'm doing I'd be happy to help a bit. 

On a tangent, holy shit [thank you so much for writing all of this. This is wildly helpful to me as someone who spent time in Emacs many years ago, moved away, and is now coming back trying to understand the state of Doom from the ground up.](https://github.com/VitalyAnkh/doom/blob/vr/config.org#doom-emacs-configuration)

**Comment by VitalyAnkh** [comment]
@devdumpling I must clarify that my emacs configuration is adapted from [Teco](https://github.com/tecosaur)'s [great configuration](https://github.com/tecosaur/emacs-config). Teco's config is so awesome that I forked it and added some of my things to it. Kudos to Teco!

**Comment by devdumpling** [comment]
Got it. Well, props either way. Learning a lot following these threads. 

Have spent the last week purely trying to tweak motion bindings and fix `which-key` maps (so really living the emacs experience).

**Comment by hlissner** [comment]
As of v2.2, modules have been moved out of core, so module development has moved to [doomemacs/modules](https://github.com/doomemacs/modules) and [doomemacs/modules-contrib](https://github.com/doomemacs/modules-contrib). If you (or anyone else here) is still interested in this, the modules-contrib repo is ready to receive PRs like this one.

If you're not interested, that's fine too. Sorry for the trouble and thanks your for your interest!

**Pull request closed without merging**
