### PR TITLE
feat(layout): add colemak layout

### LINKED ISSUE #783: Support colemak keyboard layout
Planning on trying out new layouts soon, figured maybe we should have a support module.

Might be based off https://github.com/wbolster/evil-colemak-basics ?

### PR DESCRIPTION
**Pull request by Benjamin-Davies**
Fixes #783 

The Colemak keyboard layout moves the default navigation keys (HJKL) to positions where they must be pressed by the same finger, negating some of the efficiency benefits of the layout.

This PR adds a `+colemak` option to the `:input layout` module, which remaps HJKL to the original Querty positions (HNEI), and remaps the over-ridden keys to their Querty positions. The design is based off of https://github.com/wbolster/emacs-evil-colemak-basics/blob/master/evil-colemak-basics.el, which seems to be a consensus from the issue.

### CODE REVIEW

**Comment by gagbo** [comment]
Hello,

I’m starting to get interested in this as I think I’ll change layout soon to migrate to Colemak as well. I just have a few remarks/questions :

- Why isn’t `+layout-colemak-rotate-dh` called anywhere ? Looks like there’s a variable missing (like `doom-layout-colemak-mod-dh` or something) to specify that we want the dh rotation, and then apply it.
- For the "vanilla" evil maps, I think that plainly using [your inspiration](https://github.com/wbolster/emacs-evil-colemak-basics) is better : we’ll be able to directly upstream some issues/ameliorations found, and it’s going to be easier as well to "offload" part of the documentation/effort. You can directly add it by using the `packages.el` of the module :
```lisp
;; modules/input/layout/packages.el

(when (and (featurep! :editor evil) (featurep! +colemak))
  (package! evil-colemak-basics :pin "ddea4486de929c399745713a6e616df50b22dedd"))
  
;;;;;;;;;;;;;;;;;;;;;;

;;  modules/input/layout/+colemak.el

(when (featurep! :editor evil)
  (use-package evil-colemak-basics
    :after evil
    :config
    (global-evil-colemak-basics-mode)))
```
This implementation would need that the users change their colemak related settings in their `init.el`, but it’s probably less maintenance.
- And last, one of the main reasons I did the bépo module as well was to handle `evil-collection` to be sure that the remappings would go on every mode. It seems to be missing in this PR, do you think they are unnecessary ?

Cheers,
Gerry

**Comment by azzamsa** [comment]
@Benjamin-Davies do you have any issue regarding magit-keybinding clashes with this chages?

Context:
- https://github.com/hlissner/doom-emacs/issues/783#issuecomment-1024707128

**Comment by gagbo** [comment]
ping

**Comment by Lord-Valen** [comment]
@hlissner Maybe you missed this?

**Comment by hlissner** [comment]
This was auto-closed because I deleted the `develop` branch, but I'm still interested in the functionality. I will revisit it soon.

**Pull request closed without merging**
