### PR TITLE
Update lsp-mode and remove workaround for lsp-julia

### PR DESCRIPTION
**Pull request by devmotion**
This PR bumps lsp-mode and removes the folding hack for lsp-julia.

There are multiple issues in the lsp-mode repo ([#2722](https://github.com/emacs-lsp/lsp-mode/issues/2722)), lsp-julia repo ([#23](https://github.com/gdkrmr/lsp-julia/issues/23) and [#35](https://github.com/gdkrmr/lsp-julia/issues/35)), and the LanguageServer.jl repo ([#844](https://github.com/julia-vscode/LanguageServer.jl/issues/844)) about crashes of the Julia LSP with lsp-mode due to errors caused by the folding capabilities announced by the client. One can work around these issues by enabling folding (see e.g. [here](https://github.com/gdkrmr/lsp-julia/issues/23#issuecomment-613694282)) but that is only a hack and does not fix the underlying issue. The problem is caused by a [violation of the LSP specs in lsp-mode](https://github.com/julia-vscode/LanguageServer.jl/issues/844#issuecomment-810563376) which was fixed in https://github.com/emacs-lsp/lsp-mode/pull/3593. The PR updates lsp-mode to the latest commit on the master branch which contains this fix (and some other unrelated fixes, CI passes successfully again), and hence the workaround for lsp-julia can be removed.

I tested this PR locally and could not observe any crashes of the Julia LSP anymore.

As a side note, the hack for lsp-julia did not work completely successfully for [me](https://github.com/gdkrmr/lsp-julia/issues/35#issuecomment-1168101143) and [others](https://github.com/gdkrmr/lsp-julia/issues/35#issuecomment-1102504324): I had to open a Julia file, close the crashed LSP, and then reopen the Julia file. I assume that maybe the hook was applied too late and hence did not work successfully when opening a Julia file for the first time.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [ ] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

### CODE REVIEW

**Comment by elken** [comment]
@tecosaur wdyt?

**Comment by tecosaur** [comment]
Without testing, that looks decent to me.

**Comment by devmotion** [comment]
I fixed the commit message of the first commit (bumping lsp-mode), I noticed that the commit hashes in the message body were in the wrong order.

**Comment by hlissner** [comment]
A more comprehensive (and up-to-date) bump was needed, so I did so in acae9f9, with credit. Thanks for bringing it to my attention!

**Comment by devmotion** [comment]
Thank you for the fix!

**Pull request closed without merging**
