### PR TITLE
feat(file-templates): Add javascript file templates

### PR DESCRIPTION
**Pull request by Layerex**
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

### CODE REVIEW

**Comment by jeetelongname** [comment]
How many people are using JS principally for scripts? I would assume its a minority, add to that the fact that there are so many different types of projects that js is used for I doubt this would be useful and would become a hindrance. I am curious to hear your thinking

**Comment by Layerex** [comment]
> How many people are using JS principally for scripts?

Principally? I don't know. Personally, I know at least one person, who does.

Anyways, node shebang is pretty common: [https://github.com/search?l=JavaScript&o=desc&p=1&q=%23%21%2Fusr%2Fbin%2Fenv+node&s=indexed&type=Code](https://github.com/search?l=JavaScript&o=desc&p=1&q=%23%21%2Fusr%2Fbin%2Fenv+node&s=indexed&type=Code).

For comparison: usage of [python](https://github.com/search?l=Python&o=desc&q=%23%21%2Fusr%2Fbin%2Fenv+python&s=indexed&type=Code) ([2](https://github.com/search?l=Python&q=%23%21%2Fusr%2Fbin%2Fenv+python2&s=indexed&type=Code), [3](https://github.com/search?l=Python&o=desc&q=%23%21%2Fusr%2Fbin%2Fenv+python3&s=indexed&type=Code)), [sh](https://github.com/search?l=Shell&q=%23%21%2Fusr%2Fbin%2Fenv+sh&s=indexed&type=Code), [bash](https://github.com/search?l=Shell&q=%23%21%2Fusr%2Fbin%2Fenv+bash&s=indexed&type=Code
) and [perl](https://github.com/search?l=Perl&o=desc&p=2&q=%23%21%2Fusr%2Fbin%2Fenv+perl&s=indexed&type=Code) shebangs.

**Comment by Layerex** [comment]
"use strict" is very common, so I decided to add a file template with it too.

**Review by hlissner — CHANGES_REQUESTED** [review]
I'm inclined to agree with jeet; that the shell script use-case prevalent enough to warrant it being a default. I think it'd serve better as a snippet; [in fact, one already exists](https://github.com/doomemacs/snippets/blob/master/fundamental-mode/bang). Perhaps a `"use strict"` one would make sense too?

That said, I think the `"use strict"` snippet would make more sense as a default. Would you mind removing the first commit, and renaming `__strict` to `__`?

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the late response. Thanks for your help!

**Pull request merged**
