### PR TITLE
feat(ophints): add goggles for non-evil users

### PR DESCRIPTION
**Pull request by Dev380**
This adds the goggles package as a module flag
to use goggles instead of volatile-highlights-mode as a non-evil user.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

### CODE REVIEW

**Review by hlissner — CHANGES_REQUESTED** [review]
Is there any compelling reason to keep volatile-highlights? If not, I'd rather do away with it entirely.

**Comment by Dev380** [comment]
I'm not sure how the release schedule works so I kept it in to avoid a breaking change; should vhl be removed and goggles.el be the new default when evil is off?

**Comment by Dev380** [comment]
VHL is removed

**Comment by hlissner** [comment]
I've compressed this and some other modifications to the module in 3431ddd. Thanks for your help and patience, and for bringing it to my attention!

**Pull request closed without merging**
