### PR TITLE
module: add :tools collab

### PR DESCRIPTION
**Pull request by jming422**
Add a collaborative editing module, powered by crdt.el.

@artenator and I (@jming422) are the authors of this module (we used crdt.el to write it collaboratively!), and we're offering to maintain it as best we can also.

**Some things we'd love feedback on:**
 - Keybindings -- For now we put it at the leader `SPC l`, but are very willing to change this!
 - UI look & feel -- Some of the interfaces used by crdt.el feel "vanilla Emacs-y", and we're not totally sure what to do about it. The menus for creating a new session with `crdt-share-buffer` and connecting to someone else's session using `crdt-connect` especially fall into this category - they use the `forms-mode` builtin major mode for these menus.

**Some things we still have in progress, but that shouldn't block initial review:** (all done now, yay!)
 - [x] When the host of a collaborative session kills their session, clients are only partially disconnected automatically. If the client forgets to run `crdt-disconnect`, and then they attempt to establish a new connection using `crdt-connect` later, the existence of their previous (now broken) session causes a TON of problems, basically making it necessary for them to restart Emacs. We've gotta contribute a fix to this before we'll feel comfortable marking this PR as non-draft. **Update:** We have submitted a fix which has been merged upstream [here](https://code.librehq.com/qhong/crdt.el/-/merge_requests/5)
 - [x] When the `+tunnel` flag is provided, starting or connecting a new session pops up a confusing/not-pretty `*Tuntox Proxy*` buffer in a big window. We'd like to change this so the buffer (which is basically a log) remains in the background instead. **Update:** We have merged a resolution to this upstream [here](https://code.librehq.com/qhong/crdt.el/-/merge_requests/4).
 - [x] We made an evil-collection to fix some of the crdt.el default bindings when in normal mode, and it is merged: https://github.com/emacs-evil/evil-collection/pull/673
 - [x] crdt.el provides `crdt-visualize-author-mode`, but it's faces are not very nice or easy to read with default theme settings, plus they use underlines which evoke the sense that it's an error checker instead of a collab feature. **Update:** These issues are no longer problematic on Doom default themes
 - [x] A bug seems to have appeared in crdt.el that can cause shared buffers to fall out of sync, it is tracked upstream [here](https://code.librehq.com/qhong/crdt.el/-/issues/4). **Update:** It seems to be resolved now!

Ref: https://code.librehq.com/qhong/crdt.el

Screen Shot 2022-09-02 at 5 09 25 PM

Screen Shot 2022-09-02 at 5 03 45 PM

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] My changes are visual; I've included ~before and~ after screenshots.
  - _I almost posted a picture of my empty hand for the "before" screenshot 😉_
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

### CODE REVIEW

**Comment by jming422** [comment]
Been a long time in the coming, but at last we think everything upstream and in this PR is ready to go, even the optional stuff we were looking into! Thanks all, looking forward to your feedback 😄 

As a reminder from the main description, the two areas where we want feedback the most are keybindings and UI look & feel 🔍

**Comment by port19x** [comment]
I'd love to have this to collab with other maintainers of [ani-cli](https://github.com/pystardust/ani-cli), since doom is becoming the dominant choice there.

I'm setting a 20$ bounty on the merge. 
Will be sent as one-time donation to @hlissner via github sponsors

**Comment by jming422** [comment]
Hey @port19x, thanks for the bounty and your interest! As far as the authors are concerned this PR is ready to go, but just to help with expectations, I know Henrik is both quite busy and also in the middle of a pretty big (awesome IMO!) refactor to the way modules are distributed for Doom, so it might still take a while for the dust to settle enough for this new module to make it in.

In the meantime, if you don't mind getting a bit into the weeds with Doom, you can use the module now by:
- going into your `~/.config/emacs` or `~/.emacs.d/`
- adding our fork as a Git remote
- checking out the `collab` branch
- `doom sync`

We try our best to keep it up to date with upstream, and if you do start using it, we'd love any feedback you have on the UX or anything else about the module!

**Comment by hlissner** [comment]
Sorry for the (tremendously) late review! This looks excellent, and seems merge-ready is-as. I'm not 100% on the leader keybind, but that's something I'll revisit after v3 (when I get around to reviewing Doom's UX across the board).

Anyhow, thanks for your help!

**Comment by port19x** [comment]
just sent the bounty, thx for the merge :+1:

**Pull request merged**
