### PR TITLE
feat(common-lisp): add more sly packages

### PR DESCRIPTION
**Pull request by seanfarley**
Might as well?

### CODE REVIEW

**Comment by hlissner** [comment]
Can you explain the purpose and benefit of these packages? And why they should be included by default? Are these packages that most/all Common Lisp developers will want?

**Comment by seanfarley** [comment]
I'm still learning common lisp but it seems quicklisp is pretty defacto-ish for modern development? I'm using it with a handful of projects so I admit it's a small sample.

The other two were just nice-ish ones that I thought would be nice to have but mostly just shots in the dark.

**Comment by ispringle** [comment]
Just adding my two cents here, quicklisp is used by pretty much all CL devs, it's the package repo for Lisp. I think sly-quicklisp makes sense as an addition to the CL module. sly-stepper is a good debugging tool and it extends Sly's native stickers feature nicely. I agree it also makes sense in the module. I have the readtable package installed and never use it. I'm sure more advanced CL devs might have a need for multiple readtables but it is not, in my opinion, a regular/normal part of CL dev work.

**Comment by seanfarley** [comment]
That is exactly what I'm currently setup for in my CL environments, too, hehe. I almost never have used readtables but thought, "why not?" so I'll remove that as well. Thanks for the input!

**Comment by seanfarley** [comment]
Ok, I updated the PR to remove `readtables` and think it's pretty good to know now (IMHO)

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
LGTM. Thanks again for your help!

**Pull request merged**
