### PR TITLE
Add Org LaTeX fragment resizing for `doom-big-font-mode`

### PR DESCRIPTION
**Pull request by io12**
Fixes https://github.com/hlissner/doom-emacs/issues/5580

### CODE REVIEW

**Comment by io12** [comment]
I didn't know about `image-scaling-factor` but I think it is better to regenerate the fragments at the higher resolution so they aren't blurry.

**Comment by benneti** [comment]
Just to chime in, as it is possible to use svg (dvisvgm instead of dvipng in org-preview-latex-process-alist) it might be simpler to only scale and not regenerate but switch the default in doom from png to svg (although I am not sure whether all supported emacs versions have svg support by default already).

**Comment by benneti** [comment]
``` elisp
(defadvice! +org-latex-preview-scale-a (img)
  "Make org latex preview respect `image-scaling-factor'."
  :filter-return #'org--make-preview-overlay
  (plist-put (cdr img) :scale (image-compute-scaling-factor image-scaling-factor)))
(defun org-latex-update-fragment-scale ()
  ;; remove latex previews
  (org-latex-preview '(64))
  ;; rescale compiled images
  (setq image-scaling-factor (expt text-scale-mode-step text-scale-mode-amount))
  ;; recreate latex previews
  (org-latex-preview '(16)))
(add-hook! 'text-scale-mode-hook #'org-latex-update-fragment-scale)
```
This works for me, mind the redisplay of fragments, as well as the expt instead of math-pow (the latter failed for me for negative scales)

**Comment by hlissner** [comment]
This was auto-closed because I deleted the `develop` branch, but I'm still interested in the functionality. I will revisit it soon.

**Pull request closed without merging**
