### PR TITLE
fix(mu4e): add missing icons for mu 1.8.X

### LINKED ISSUE #6609: Mu4e headers display has irregular line heights with mu 1.8.X due to double-height circle-letter characters like Ⓛ
### What did you expect to happen?

I expect mu4e to look normal, with each line displayed at roughly the same height, as it did when using mu 1.6.X.

### What actually happened?

Any mu4e header line containing circled letters, e.g., ⓁⓅⒸ, are displayed at double height, which causes those lines to be displayed at double height, which makes the mu4e headers display look really weird. 

I would provide a screenshot, except that would reveal private emails. 

### Describe your attempts to resolve the issue

I was able to narrow it down to [these lines in mu4e](https://github.com/djcb/mu/blob/master/mu4e/mu4e-headers.el#L242-L244):  

```elisp
(defvar mu4e-headers-list-mark      '("s" . "Ⓛ") "Mailing list.")
(defvar mu4e-headers-personal-mark  '("p" . "Ⓟ") "Personal.")
(defvar mu4e-headers-calendar-mark  '("c" . "Ⓒ") "Calendar invitation.")
```

Doom has [a custom config which rewrites/prettifies many of the default mu4e icons](https://github.com/doomemacs/doomemacs/blob/master/modules/email/mu4e/config.el#L128-L136), but that hasn't been extended to `mu4e-headers-personal-mark` or `-calendar-mark`, so there is an inconsistent display of those characters, at least on my system. 

I tried to find which fonts provide the circled letters, and it looks like they're mostly CJK fonts, which might explain why they're double-height. 

A workaround, although not the prettiest, is just to do something like: 

```elisp
(defvar mu4e-headers-list-mark      '("s" . "L") "Mailing list.")
(defvar mu4e-headers-personal-mark  '("p" . "P") "Personal.")
(defvar mu4e-headers-calendar-mark  '("c" . "C") "Calendar invitation.")
```

But really what we need is some all-the-icons glyph which is correctly sized. 

### Steps to reproduce

1. Enable mu4e in doom modules
2. Ensure that you have the latest `mu` installed, i.e., 1.8.X
3. Ensure that you have some font installed which contains circle letters at double height
4. Call mu4e and jump to an inbox
5. Notice that the headers are all out of whack, since there are some double-height circled letters

### System Information

https://pastebin.com/FL6nczcP

### PR DESCRIPTION
**Pull request by JonathanReeve**
Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.

Fixes #6609

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [X] Any relevant issues or PRs have been linked to.

### CODE REVIEW

**Comment by tecosaur** [comment]
I just tried this out. It mostly looks fine, but the list-icon was much too big and dominant. I tried a few other things and think `(+mu4e-normalised-icon "sitemap" :set "faicon")` is a better fit in a few ways.

**Comment by JonathanReeve** [comment]
Nice. That's an improvement. Just added it to the PR.

**Review by hlissner — CHANGES_REQUESTED** [review]
Some extra git history snuck into this PR. Could you rebase it back onto `master`?

**Comment by JonathanReeve** [comment]
I think I've managed to clean it up. It should be all good to be merged, now.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Excellent. Thanks for your help!

**Pull request merged**
