### PR TITLE
docs(corfu): turning off auto-completion

### PR DESCRIPTION
**Pull request by 45mg**
Document how to turn off auto-completion.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

### CODE REVIEW

**Comment by hlissner** [comment]
Unsetting `corfu-auto` should be enough. Why modify `corfu-auto-commands` as well?

**Comment by 45mg** [comment]
> Unsetting `corfu-auto` should be enough. Why modify `corfu-auto-commands` as well?

I'm not sure why, but it doesn't turn off until I do the latter. Could either of you test with just `(setq corfu-auto nil)` and see if it works?

**Comment by LemonBreezes** [comment]
> > Unsetting `corfu-auto` should be enough. Why modify `corfu-auto-commands` as well?
> 
> I'm not sure why, but it doesn't turn off until I do the latter. Could either of you test with just `(setq corfu-auto nil)` and see if it works?

Yeah, for me, just setting `corfu-auto` to nil did not work either. Seems like it might be a bug in Corfu. Maybe.

**Comment by 45mg** [comment]
I tested this on a fresh install. Same thing.

**Comment by hlissner** [comment]
Seems to work fine for me, but only at startup. You two sure you're not trying to `M-: (setq corfu-auto nil)` in a running session? 

Corfu consults [`corfu-auto` once, when `corfu-mode` is activated](https://github.com/minad/corfu/blob/c1e7b6190b00158e67347b4db0a8f7964e5d2f8b/corfu.el#L1324). Changing `corfu-auto` won't affect pre-existing `corfu-mode`-enabled buffers.

**Comment by hlissner** [comment]
Unsetting `corfu-auto` disables auto completion in vanilla Emacs as well, as far as I can tell, so for the time being I've reduced this to only unsetting `corfu-auto` in 1598444 until I find an explanation for the behavior you two are seeing. Thanks for bringing this to my attention, in any case!

**Pull request closed without merging**
