### PR TITLE
docs(rust): add missing +tree-sitter flag

### PR DESCRIPTION
**Pull request by jotare**
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

### CODE REVIEW

**Comment by jeetelongname** [comment]
Ah good catch! LGTM

**Comment by KarthikNayak** [comment]
I see this is also missing for Go and https://docs.doomemacs.org/latest/?#/modules/tools doesn't even show tree-sitter.

**Comment by jeetelongname** [comment]
Checking the tree you can see that the tree sitter flag is not missing from the [readme](https://github.com/doomemacs/doomemacs/tree/master/modules/lang/go) I am not sure where else you would mean. 

as for the docs site. thats outdated. Its a known issue.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Good catch. Thanks for the help!

**Pull request merged**
