### PR TITLE
feat(corfu): `both` option for RET behavior

### PR DESCRIPTION
**Pull request by 45mg**
Adds a new value of `+corfu-want-ret-to-confirm` to cover the case where the user wants to select the candidate as well as perform the normal behavior of RET.

Also, the logic for RET behavior has been refactored for clarity, and the variable's documentation has been clarified a little.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

### CODE REVIEW

**Comment by LemonBreezes** [comment]
I like this refactor and the `both` option. Update the README.org to reflect this change too.

**Comment by 45mg** [comment]
The default behavior has not been changed, and the README didn't document the variable's options before, so I didn't touch it. Is it really necessary?

**Comment by LemonBreezes** [comment]
> The default behavior has not been changed, and the README didn't document the variable's options before, so I didn't touch it. Is it really necessary?

Hm. It does currently mention the variable options before, though that is not necessary in general probably.

**Comment by 45mg** [comment]
Oh, my bad, it does. I just missed it. I'll add another commit in a bit.

**Comment by 45mg** [comment]
Updated the docs as requested.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the delay. I've merged this in 10484de. Thanks again for your help!

**Pull request merged**
