### PR TITLE
fix(ligatures): set-font-ligatures! reset on nil

### PR DESCRIPTION
**Pull request by andresilva**
Replace this with a summary of what you've changed and why, followed by a list of issues it affects, if any.

Fix: #7433
Ref: #7433
Close: #7433

https://github.com/doomemacs/doomemacs/issues/7433#issuecomment-1729267699

cc @gagbo

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

### CODE REVIEW

**Comment by andresilva** [comment]
FWIW I still find the interface of this function to be weird. Since you first need to call this function with `nil` to clean up the existing ligatures for a certain mode, and then do another call with the ligatures you want. IMO calling this function should reset the existing ligatures for that mode and then set the given ligatures, that's what I would expect from something called "set".

**Comment by gagbo** [comment]
> FWIW I still find the interface of this function to be weird. Since you first need to call this function with `nil` to clean up the existing ligatures for a certain mode, and then do another call with the ligatures you want. IMO calling this function should reset the existing ligatures for that mode and then set the given ligatures, that's what I would expect from something called "set".

The reason for making this additive by default is that it allows other modules to add ligatures using the same interface without worrying about other calls or order of the calls. Theoretically the reset with `nil` is only called once in user config if you want to reclaim full control of the ligations happening. I guess we could split the `set-font-ligatures` in 2, 1 `add` and 1 `reset`, but always resetting is going to make debugging user issues a lot harder when file load order starts to become relevant

**Review by gagbo — APPROVED** [review]
And yeah, I fully missed that having an explicit `nil` argument would change the `&rest` value. Thanks for that!

**Comment by andresilva** [comment]
> The reason for making this additive by default is that it allows other modules to add ligatures using the same interface without worrying about other calls or order of the calls. Theoretically the reset with `nil` is only called once in user config if you want to reclaim full control of the ligations happening. I guess we could split the `set-font-ligatures` in 2, 1 `add` and 1 `reset`, but always resetting is going to make debugging user issues a lot harder when file load order starts to become relevant

Hadn't considered this, makes sense. Thanks for the explanation.

**Comment by andresilva** [comment]
ping

**Comment by hlissner** [comment]
LGTM! Sorry for taking so long to get around to this. Thanks for your help!

**Pull request merged**
