### PR TITLE
module: add `:lang graphviz`

### PR DESCRIPTION
**Pull request by nbfalcon**
- org-babel
- graphviz-dot-mode -> syntax highlighting
- error-checking using flycheck
- doom doctor

I've used lang/plantuml as a template (cp -r).

- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] I am blindly checking these off.
- [X] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

### CODE REVIEW

**Comment by peterhoeg** [comment]
Feel free to use/incorporate any of this from my own graphviz config:


We should set `graphviz-dot-dot-program` to others like `nwdiag` dynamically
when opening a `.nwdiag` file.

```lisp
    (package! graphviz-dot-mode)
    (package! ob-blockdiag)
```

```lisp
    (use-package! graphviz-dot-mode
      :mode "\\.\\(diag\\|dot\\|nwdiag\\|rackdiag\\)\\'"
      :init
      (after! org
        (add-to-list 'org-src-lang-modes
                     '("dot" . graphviz-dot)))
      :config
      (cl-defun +format-graphviz (&key buffer scratch callback &allow-other-keys)
        "Format graphviz graphs."
        (with-current-buffer scratch
          (let ((inhibit-message t)
                (message-log-max nil))
            (goto-char (point-min))
            (graphviz-dot-indent-graph))
          (funcall callback)))
    
      (when (and (not (treesit-available-p))
                 (modulep! :lang graphviz +tree-sitter))
        (add-hook 'graphviz-dot-mode-hook #'tree-sitter! 'append))
      (after! tree-sitter
        (set-tree-sitter-lang! 'graphviz-dot-mode 'dot))
      (when (modulep! :completion company)
        (set-company-backend! 'graphviz-dot-mode 'company-graphviz-dot-backend))
      (setq graphviz-dot-view-command "kde-open5 %s") ;; doesn't work, need a proper viewer
    
      (enable-auto-formatter! 'graphviz-dot-mode)
      (set-formatter! 'graphviz-dot-mode #'+format-graphviz :modes '(graphviz-dot-mode))
    
      (map! :map graphviz-dot-mode-map
            :localleader
            :desc "External view" :nv "e" #'graphviz-dot-view
            :desc "Preview"       :nv "p" #'graphviz-dot-preview
            :prefix ("t" . "toggle")
            :desc "Preview"       :nv "p" (cmd! (if graphviz-dot-auto-preview-on-save
                                                    (graphviz-turn-off-live-preview)
                                                  (graphviz-turn-on-live-preview)))))
```

It has admittedly been a while since I've used it.

**Comment by raszi** [comment]
Enabling this module breaks the earlier org-mode integration with graphviz.

A previous org file like this:

```org
#+begin_src dot :file example.svg
digraph G {
    foo -> bar
}
#+end_src
```

When I hovered the source block and executed `org-ctrl-c-ctrl-c` it generated the `example.png` correctly. With this module enabled doing the same throws a warning message and the file is not generated even though I have the `dot` CLI installed.

```
No org-babel-execute function for dot!
```

**Comment by hlissner** [comment]
> Enabling this module breaks the earlier org-mode integration with graphviz.

Where is that integration supposed to come from, exactly? Looking through `graphviz-dot-mode`'s source, there is no `org-babel-execute:dot`.

**Comment by hlissner** [comment]
Should be fixed in be422c4.

**Comment by raszi** [comment]
It works! Thank you!

**Pull request closed without merging**
