### PR TITLE
bump: :core (Deal with new NonGNU ELPA recipe format)

### LINKED ISSUE #6960: Unexpected runtime error running doom cli (`(stringp afternoon-theme)`)
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

Running `doom sync` `doom upgrade` etc. without error.

### Current behavior

When running `doom` cli some unexpected runtime error occurs:

```
x There was an unexpected runtime error
  Message: Wrong type argument
  Details: (stringp afternoon-theme)
  Backtrace:
    (intern afternoon-theme)
    ((closure ((package . gnu-elpa-mirror) use-package-pre-ensure-function u...
    (cl--position gnu-elpa-mirror ((afternoon-theme :url "https://github.com...
    (cl-position gnu-elpa-mirror ((afternoon-theme :url "https://github.com/...
    (cl-find gnu-elpa-mirror ((afternoon-theme :url "https://github.com/osen...
    (straight-recipes-nongnu-elpa--translate (cl-find package (straight-reci...
    (straight-recipes-nongnu-elpa-retrieve gnu-elpa-mirror)
    (apply straight-recipes-nongnu-elpa-retrieve gnu-elpa-mirror)
    (let ((default-directory (if local-repo (straight--repos-dir local-repo)...
    (let* ((--cl-rest-- recipe) (local-repo (car (cdr (plist-member --cl-res...
    (let ((recipe (straight--convert-recipe name cause))) (let* ((--cl-rest-...
    (let ((straight--recipe-repository-stack (cons name straight--recipe-rep...
  ! Wrote extended backtrace to ~/.emacs.d/.local/logs/cli.doom.221125120618.19303.error
✓ Finished in 0.22100s
```
[cli.doom.221125123224.19611.error.txt](https://github.com/doomemacs/doomemacs/files/10088640/cli.doom.221125123224.19611.error.txt)

### Steps to reproduce

Running `doom sync` or `doom upgrade` or `doom doctor`.

### System Information

https://gist.github.com/neolee/d9743798ab05e6165448aefb141c8dc2

### PR DESCRIPTION
**Pull request by rafa-dot-el**
Update `straight.el` ([Straight.el issue](https://github.com/radian-software/straight.el/pull/1013))

Fixes #6960
References #6960

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [X] Any relevant issues or PRs have been linked to.

### CODE REVIEW

**Comment by gagbo** [comment]
Hello,

Thanks for your time making the commit, I'm not entirely sure it'll go as-is though, because it doesn't follow the commit conventions used in the project, Not blaming you, they are tricky to find and that's part of the "contributor experience" that is meant to get a lot better by the end of current Doom sprint from Henrik.

So while it is a welcome PR, it'll probably get closed by another commit during the next batch from Henrik, just letting you know.

Cheers

**Comment by rafa-dot-el** [comment]
Hello @gagbo, thanks for taking your time and looking at my PR. I tried my best to follow the commit standards, could you point out where I missed or which points I should improve? I've no problem rewriting it, I got this tasks by the fact that was a small amount of work so I could get onboarded on the project and learn the patterns.

**Comment by gagbo** [comment]
Oh yeah sorry I meant to find the documentation but didn't find it. You can check the last bump commit to see : https://github.com/doomemacs/doomemacs/commit/2b07fd1dd834c88a679dbbe9ff56062782140422

**Comment by rafa-dot-el** [comment]
thanks for the direction, I updated accordingly, could you please check?

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks for the help!

**Pull request merged**
