### PR TITLE
tweak(elixir): guard alchemist.el with feature flag

### PR DESCRIPTION
**Pull request by merrickluo**
I found that https://github.com/hlissner/doom-emacs/pull/5031 is closed due to stale, but I think the idea is still valid.

### CODE REVIEW

**Comment by iyefrat** [comment]
Since this is a breaking change (alchemist users need to manually add the feature flag to keep their setup working), Can you please reword the type/scope to `refactor!(elixr)`, and document why this is needed in the commit body with
```
BREAKING CHANGE: lorep ipsum etc etc
```
see the [commit conventions](https://gist.github.com/hlissner/4d78e396acb897d9b2d8be07a103a854) for more details.

**Comment by cwlbraa** [comment]
elixir-ls + eglot works so much dramatically better without alchemist, it's almost criminal. Maybe the right thing to do and a way to make this somewhat more backwards-compatible is to make Elixir similar to other lsp-capable language modules and turn off alchemist when lsp is enabled. This way we don't break people who haven't configured anything, but we improve the experience of those who have already setup elixir-ls.

**Comment by merrickluo** [comment]
@cwlbraa Thanks, that also makes sense to me. My complaint is also that I have to disable alchemist manually after enabling lsp. 

@iyefrat, so, I updated the PR to use the `+lsp` flag instead of adding a new one,  I read the commit convention, but still not sure this counts as `refactor` or `tweak` after the change, I'm keeping tweak right now, but I'm happy to change it if it does not fit.

**Comment by diannasoriel** [comment]
I think this PR is very much necessary, alchemist and lsp/eglot don't really work well together, therefore disabling it with LSP is almost required for Elixir development with Doom at this point.

**Comment by merrickluo** [comment]
I think his is still relevant.

**Comment by merrickluo** [comment]
changed target to master

**Comment by bhankas** [comment]
Is this PR still relevant? I just started learning Elixir and don't understand tooling perfectly. But if it results in better experience, maybe good time to rebase on latest master changes and merge? Even if just confirmation, I can take it forward.

**Comment by merrickluo** [comment]
you can achieve the same thing with `(package! alchemist :disable t)` in
your `packages.el`, I also think it's better to just remove alchemist since
it's unmaintained for almost 5 years now.

bhankas ***@***.***> writes:

> Is this PR still relevant? I just started learning Elixir and don't understand tooling perfectly. But if it results in better experience, maybe
> good time to rebase on latest master changes and merge? Even if just confirmation, I can take it forward.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.


--
Thanks.
Merrick Luo

**Comment by hlissner** [comment]
@merrickluo Sorry for taking so long to get back to this, but I'm looking into resolving this now and wanted to know if it still makes sense to remove alchemist altogether? Is there any merit to keeping it? If they are equal, I'd rather rely on lsp-mode.

**Comment by ckruse** [comment]
Alchemist is de facto dead. It should be dropped completely.

**Comment by hlissner** [comment]
Understood. Done as of 221e75e. Thanks for the help!

**Comment by adrianbrink** [comment]
Is there still support for `iex` and `mix` using this package, because from the config files it seems that this was provided by alchemist.

**Pull request closed without merging**
