### PR TITLE
Org knit

### PR DESCRIPTION
**Pull request by tecosaur**
See https://discourse.doomemacs.org/t/org-knit-development/1432 for task list and discussion.

```
Usage: org-knit [OPTIONS] [TARGETS...]

A command line interface for weaving (exporting) and tangling org-mode files.
TARGETS can be files of folders (which are searched for org files recursively).

This is useful for automated generation of files,
and integration with other scripts.

Example:
  org-knit some-file.org
  org-knit -f pdf book/chapters/
  org-knit -t -f ascii,md scripts.org

Options:
  -a, --alias [FORMATS]	Give the org function called by a particlar alias.
  			List all aliases when no format or other arguments are given
  -c, --clean		Delete all non-org files which share their basename
  -e, --exec		Execute src blocks in the file before exporting
  -f, --format FORMATS	Export formats (comma seperated, no space), html by default
  -j, --jobs		Number of jobs executed in parallel (14 by default)
  -l, --load		Elisp files to load
  -s, --sync		Perform the exporting/tangling synchronously
  -t, --tangle		Also tangle the file(s).
  			See org-tangle for more advanced functionallity
  -q, --quiet		Suppress the output of status information
  -   			Output to stdout instead of writing to files
```

#### `org-knit -s -f ascii,md,html *.org`
image

### CODE REVIEW

**Comment by tecosaur** [comment]
Update: after a long delay I'm coming back to this :slightly_smiling_face:

**Comment by tecosaur** [comment]
A wonderful bird is the pelican,
  His bill can hold more than his beli-can.
       He can take in his beak
       Food enough for the week;
  But I'm damned if I see how the heli-can.

**Comment by tecosaur** [comment]
Delayed but not abandoned.

**Comment by hlissner** [comment]
This was auto-closed because I deleted the `develop` branch, but I'm still interested in the functionality. I will revisit it after v3.

**Comment by tecosaur** [comment]
NP. Likewise, happy to revisit later. I think this is 80-90% there, and neat functionality to have.

**Pull request closed without merging**
