### PR TITLE
feat(vertico): completion highlights a la ivy

### PR DESCRIPTION
**Pull request by Dev380**
Adds completion highlighting that works similarly to ivy/counsel's one (which is enabled by default). It'll highlight enabled major/minor modes and directories in a different face. On by default.

Before:
20240304_19h20m07s_grim
After:
20240304_19h20m45s_grim

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] My changes are visual; I've included before and after screenshots.
- [x] (N/A) Any relevant issues or PRs have been linked to.

### CODE REVIEW

**Comment by Dev380** [comment]
This is basically directly copy-pasted from [vertico's wiki](https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting). I am not sure why they made the M-x buffer reverse in this snippet so I removed that. Some things I'm unsure about:

- is it common practice here to add attribution to the wiki with a link comment?
- should I remove the commented-out code from the wiki or leave it? I left it in for now.

**Comment by hlissner** [comment]
That this overrides matches (e.g. the `xah`) is undesirable. Can it be modified to prioritize the match over the type?

**Review by hlissner — CHANGES_REQUESTED** [review]
> is it common practice here to add attribution to the wiki with a link comment?

Yes, especially if it's copied verbatim, in these two ways:

1. A comment over the relevant part with something like:

  ```elisp
  ;; From https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting
  ```

2. And a `Ref:` line at the bottom of the git commit:
  
  ```
  feat(vertico): completion highlights a la ivy
  
  Adds completion highlighting that works similarly to ivy/counsel's
  one (which is enabled by default). It'll highlight enabled major/minor
  modes and directories in a different face. On by default.
  
  Ref: https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting
  ```

Please reword the git commit and add the comment.

> should I remove the commented-out code from the wiki or leave it? I left it in for now.

Please do. All the comments from the snippet, in fact. They're redundant with the code.

**Comment by Dev380** [comment]
> That this overrides matches (e.g. the xah) is undesirable. Can it be modified to prioritize the match over the type?

I guess I'll try to implement this myself, but I'll need to look through the code a bit more to understand it so I think I'll convert this to a draft until then.

**Comment by Dev380** [comment]
> > is it common practice here to add attribution to the wiki with a link comment?
> 
> Yes, especially if it's copied verbatim, in these two ways:
> 
>     1. A comment over the relevant part with something like:
> 
> 
> ```emacs-lisp
> ;; From https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting
> ```
> 
>     2. And a `Ref:` line at the bottom of the git commit:
> 
> 
> ```
> feat(vertico): completion highlights a la ivy
> 
> Adds completion highlighting that works similarly to ivy/counsel's
> one (which is enabled by default). It'll highlight enabled major/minor
> modes and directories in a different face. On by default.
> 
> Ref: https://github.com/minad/vertico/wiki#candidate-display-transformations-custom-candidate-highlighting
> ```
> 
> Please reword the git commit and add the comment.
> 
> > should I remove the commented-out code from the wiki or leave it? I left it in for now.
> 
> Please do. All the comments from the snippet, in fact. They're redundant with the code.

Okay, thank you, I'll do that

**Comment by Dev380** [comment]
> That this overrides matches (e.g. the `xah`) is undesirable. Can it be modified to prioritize the match over the type?

This should be resolved now, the blue font lock now displays over the purple.

**Comment by Dev380** [comment]
20240307_18h37m57s_grim
Here's what it looks like now.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks for your help!

**Comment by l2dy** [comment]
Does `vertico-multiform` need to be added to `modules/completion/vertico/packages.el`?

**Comment by hlissner** [comment]
@l2dy No. It's [part of the vertico package](https://github.com/minad/vertico/blob/main/extensions/vertico-multiform.el).

**Pull request merged**
