### PR TITLE
module: add :lang janet

### PR DESCRIPTION
**Pull request by wojtyniak**
Adding support for the Janet language (https://janet-lang.org/) using
janet-mode (https://github.com/ALSchwalm/janet-mode) and inf-janet
(https://github.com/velkyel/inf-janet/blob/master/inf-janet.el)

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to. (there's none)

### CODE REVIEW

**Comment by peterhoeg** [comment]
I've been using my own janet module. I am using https://codeberg.org/sogaiu/a-janet-mode.git instead of `janet-mode` on melpa. And there's also ijanet-mode for interactive use:
```elisp
(package! a-janet-mode
  :recipe (:type git
           :repo "https://codeberg.org/sogaiu/a-janet-mode.git"
           :branch "main"
           :files ("*.el" "*.janet" "highlights")))

(package! ijanet-mode
  :recipe (:host github :repo "serialdev/ijanet-mode"))
```

And a few missing config options as a consequence:
```elisp
(use-package! ijanet-mode
  :commands (ijanet-eval-buffer ijanet-eval-line ijanet-eval-region ijanet-eval-sexp-at-point)
  :init
  (map! :localleader
        :map (a-janet-mode-map janet-mode-map)
        (:prefix-map ("e" . "eval")
         :desc "buffer" "b" #'ijanet-eval-buffer
         :desc "sexp"   "e" #'ijanet-eval-sexp-at-point
         :desc "line"   "l" #'ijanet-eval-line
         :desc "region" "r" #'ijanet-eval-region)))

(when (featurep! :editor format)
  (after! format-all
    (define-format-all-formatter janet
      (:executable)
      (:install)
      (:modes janet-mode)
      (:format
       (format-all--buffer-native
        'janet-mode
        (cmd! (indent-region (point-min) (point-max))))))))

(eval-when! (featurep! +tree-sitter)
  (add-hook! 'janet-mode-hook
             #'turn-on-tree-sitter-mode
             #'+tree-sitter-keys-mode))
```

**Comment by jeetelongname** [comment]
FYI its now just
```elisp
(eval-when! (featurep! +tree-sitter)
  (add-hook! 'janet-mode-hook #'tree-sitter!))
```
if you want to enable tree sitter :wink: (though I am not sure of a janet grammer)

**Comment by peterhoeg** [comment]
> if you want to enable tree sitter 😉 (though I am not sure of a janet grammer)

There isn’t one (or at least wasn’t one when I set this up), which is why it’s guarded behind `(featurep! +tree-sitter)'

Will be great to have your tree-sitter module in BTW!!

**Comment by yuuyins** [comment]
@peterhoeg i'm also using a-janet-mode, but i've found some issues with parenthesis completion, and more. on the other hand i'ven using github.com/sogaiu/ajrepl and a find it pretty good.

```
#+begin_src emacs-lisp :tangle config.el
(use-package! a-janet-mode)
#+end_src

#+begin_src emacs-lisp :tangle packages.el
(package! ajrepl
  :recipe (:type git
           :host github
           :repo "sogaiu/ajrepl"
           :files (:defaults ("ajrepl/"
                              "ajrepl/*")))
  :pin "d1daac0dbc70a261a9f5f807dbbc4dbb67ec37ee")
#+end_src
```

**Comment by wojtyniak** [comment]
Closing as I don't work on this PR anymore

**Pull request closed without merging**
