### PR TITLE
Update config.el

### PR DESCRIPTION
**Pull request by edmundmiller**
Fix doom leader not working in pdf mode. 

Replaces SPC default that moves the document down a page.

### CODE REVIEW

**Comment by UndeadKernel** [comment]
By removing the "q" binding, wouldn't that disable quitting a PDF for non-evil users?

**Comment by Emiller88** [comment]
It keeps the q binding(I think it's more important than recording a macro in a PDF)

**Comment by UndeadKernel** [comment]
The "q" binding seems to be replaced rather than kept.

**Comment by Emiller88** [comment]
@UndeadKernel my mistake I'll fix that!

**Comment by UndeadKernel** [comment]
A small detail still remains :)
Because you added the ":n" before the "q", now the binding will only work for evil users. For non-evil users, we wish to keep the original rule without the ":n".

**Comment by Emiller88** [comment]
So would it be this?
```
(map! (:map (pdf-view-mode-map)
         "q" #'kill-this-buffer
         doom-leader-key nil))
```

**Comment by hlissner** [comment]
@Emiller88 That should do it. Though, no need for the parentheses in this case:

```elisp
(map! :map pdf-view-mode-map
      "q" #'kill-this-buffer
      doom-leader-key nil)
```

**Comment by Emiller88** [comment]
@hlissner Fixed it. Thanks, @UndeadKernel!

**Pull request merged**
