### PR TITLE
Glamorous doc links

### PR DESCRIPTION
**Pull request by tecosaur**
This is not the final form of the Docs, but it allows for this work to be reorganised and then further improved down the line.

For fun, here are a few screenshots of the Org docs with these changes.

image

image

image

### CODE REVIEW

**Comment by elken** [comment]
Think this has been yak shaved to death now xD Keen to get this in

**Comment by tecosaur** [comment]
I think there's still more yack shaving to go, but I think it's at least reached the point we can all agree it's an *improvement* :slightly_smiling_face:

**Comment by elken** [comment]
> I think there's still more yak shaving to go, but I think it's at least reached the point we can all agree it's an _improvement_ slightly_smiling_face

It was always an improvement :P

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Great work, as usual! Thanks again for your help!

**Pull request merged**
