### PR TITLE
feat(corfu): update smart tab completion

### PR DESCRIPTION
**Pull request by LemonBreezes**
This commit updates the smart tab functionality so that:
1. The only functionality checked is for the modules that are enabled.
2. The priority of the TAB behavior is tunable by the user.

This also updates the TAB behavior for the Corfu module to be `indent-for-tab-command` instead of `completion-at-point` so that users can use the TAB key to indent their code and navigating Org tables.

This also addresses #7372 by checking overriding-terminal-local-map, as that is used by Embark.

Fix: #7733
Fix: #7372

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] Any relevant issues or PRs have been linked to.

### CODE REVIEW

**Comment by andresilva** [comment]
Changes in this PR worked great for me and fixed the issues I was having with snippets integration.

Not really related to this PR, but one thing not working properly is committing the "no candidate" with RET. It exits corfu as expected, but also adds a newline, which IMO it shouldn't do.

**Comment by LemonBreezes** [comment]
> Changes in this PR worked great for me and fixed the issues I was having with snippets integration.
> 
> Not really related to this PR, but one thing not working properly is committing the "no candidate" with RET. It exits corfu as expected, but also adds a newline, which IMO it shouldn't do.

Thanks. I looked and I saw I had accidentally overwritten the smart RET code with an older version of that code and have just corrected that & force-pushed.

**Comment by prashantvithani** [comment]
> > Changes in this PR worked great for me and fixed the issues I was having with snippets integration.
> > Not really related to this PR, but one thing not working properly is committing the "no candidate" with RET. It exits corfu as expected, but also adds a newline, which IMO it shouldn't do.
> 
> Thanks. I looked and I saw I had accidentally overwritten the smart RET code with an older version of that code and have just corrected that & force-pushed.

That reminds me, this is actually fixing a behaviour where `TAB` triggers `completion-at-point` instead of indentation (where it should indent). @hlissner, does it make sense to check this in as a fix instead of a feature?

**Comment by TheJJ** [comment]
Just the fix is in #7746 😁

**Comment by JasZhe** [comment]
I had some really hacky stuff to make corfu behave somewhat nicer when hitting tab until I stumbled upon this fix. Cherry picked this on top of master and it Works like a charm, solved all my issues with the corfu module. Thank you!

**Comment by Schievel1** [comment]
I just did the same and cherry picked this branch over master. Tab indentation works fine so far with this, but my setup does not anymore. I set up TAB to accept the completion. 
```
(map! :map corfu-map
        "TAB" #'corfu-complete
...
```
But it always cycles candidates on tab. How can I set it up that TAB is not touched by this?

**Comment by LemonBreezes** [comment]
> I just did the same and cherry picked this branch over master. Tab indentation works fine so far with this, but my setup does not anymore. I set up TAB to accept the completion.
> 
> ```
> (map! :map corfu-map
>         "TAB" #'corfu-complete
> ...
> ```
> 
> But it always cycles candidates on tab. How can I set it up that TAB is not touched by this?
> 
> ```
> (use-package! corfu
>   :init
>   (setq
>    corfu-auto-delay 0.5
>    corfu-auto-prefix 2
>    corfu-min-width 30
>    corfu-preselect nil
>    corfu-preview-current nil
>    +corfu-want-ret-to-confirm nil
>    +corfu-want-tab-prefer-expand-snippets t
>    corfu-popupinfo-max-height 30)
>   (corfu-popupinfo-mode)
>   (corfu-history-mode)
>   (custom-set-faces!
>     `(corfu-current
>       :background ,(doom-blend (doom-color 'blue) (doom-color 'bg-alt) 0.3)
>       :extend t))
>   :config
>   (map! :map corfu-map
>         "TAB" #'corfu-complete
>         "C-y" #'corfu-complete
>         "<tab>" #'corfu-complete
>         "S-TAB" nil
>         "<backtab>" nil))
> ```
> 
> C-y does not work either to accept the completion.
> 
> FWIW I got this going with `+corfu-want-tab-prefer-navigating-snippets t`. I don't really understand this without reading the code, so maybe needs a bit more documentation. Edit: Nope, does not work after restarting emacs. I don't know what I did there yesterday, but apparently it has something to do in what order I evaled something.

That's because the `TAB` or `<tab>` are bound in insert state and so is `C-y`. Insert state keybindings take priority over global keybindings if insert state is enabled. This also happens if you use the Company module. I added an explanation to the troubleshooting section of the README.

**Comment by Schievel1** [comment]
You're right. This is a different story. On my native Gentoo Linux' emacs TAB indents and when the line is already indented, it pops up the corfu childframe. In my Gentoo on WSL emacs it always brings up the corfu childframe, regardless if the line is not indented. This confused me. Both have the same config. 

At least I can confirm, that setting the keys with :gi worked on my native Gentoo.

**Comment by shroomist** [comment]
great, thanks, also confirming that this does solve another issue - TAB navigation (jump to next cell) in org-table was broken.
looking forward to see this upstream, thanks!

**Comment by LemonBreezes** [comment]
Just pushed a fix for the `:+corfu-want-tab-prefer-navigating-org-tables` and `+corfu-want-tab-prefer-navigating-snippets` options.

**Comment by maikol-solis** [comment]
I hope this PR gets merged soon. 🙏🏻

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for taking so long to get to this; I have a number of issues with the implementation, but it's taking me longer than I anticipated to put together a better one, so I'll merge this for the time being so folks can get their TAB key back. Thanks for your help and patience!

**Pull request merged**
