### PR TITLE
fix(god): enable god-mode on init

### LINKED ISSUE #6954: God mode is not enabled on all buffers on start-up
### I confirm that...

- [X] I have searched the [issue tracker](https://github.com/doomemacs/doomemacs/issues), [documentation](https://docs.doomemacs.org), [FAQ](https://docs.doomemacs.org/-/faq), [Discourse](https://discourse.doomemacs.org), and [Google](https://google.com), in case this issue has already been reported/resolved.

- [X] I have read "[How to Debug Issues](https://doomemacs.org/d/how2debug)", and will use it to provide as much information about this issue as possible.

- [X] The issue can be reproduced on the **latest** available commit of Doom.

- [X] The issue can be reproduced on a stable release of Emacs, such as 27 or 28. *(Doom does not support development builds like 29+ or any version ending in .50 or .9x)*

### Expected behavior

When Emacs starts up, God mode (`god-local-mode`) should be enabled on all buffers.

### Current behavior

When Emacs starts up, God mode is not enabled on all buffers.

This was broken through 7a2be67.
I've fixed this by using the `doom-after-modules-config` instead of `doom-after-modules-init` (in `modules/editor/god/config.el`):
```diff
modified   modules/editor/god/config.el
@@ -1,7 +1,7 @@
 ;;; editor/god/config.el -*- lexical-binding: t; -*-
 
 (use-package! god-mode
-  :hook (doom-after-modules-init . god-mode-all)
+  :hook (doom-after-modules-config . god-mode-all)
   :config
   (add-hook 'post-command-hook #'+god--configure-cursor-and-modeline-h)
   (add-hook 'overwrite-mode-hook #'+god--toggle-on-overwrite-h)
```

I would have submitted a PR too, but `modules/**/*` is in the do-not-PR list.

### Steps to reproduce

1. Enable `:editor god` module.
2. Run `doom sync`.
3. Start Emacs.

### System Information

https://pastebin.com/nbuHTZTA

### PR DESCRIPTION
**Pull request by darth10**
Enabling god-mode was broken in 7a2be67efadf63f28b948849240f78508579fb3e.
Fixes #6954.
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [X] Any relevant issues or PRs have been linked to.

### CODE REVIEW

**Review by hlissner — DISMISSED** [review]

**Comment by darth10** [comment]
Rebased and bumped `:editor god`.

**Review by hlissner — APPROVED** [review]

**Review by hlissner — CHANGES_REQUESTED** [review]
Sorry for the nitpick, but would you mind rewording the `fix` commit to include fix and amend lines in its footer:

```
fix(god): enable god-mode on init

Enabling god-mode was broken in 7a2be67.

Fix: #6954
Amend: 7a2be67efadf
```

**Comment by darth10** [comment]
> Sorry for the nitpick, but would you mind rewording the fix commit to include fix and amend lines in its footer:

No worries, that's all done!

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Excellent work! Thanks for your help!

**Pull request merged**
