### PR TITLE
fix(rest): error defining as dynamic an already lexical var

### LINKED ISSUE #6073: Problem with HTTPS in restclient with module "rest"
### What did you expect to happen?

Last time my Doom Emacs can't work in restclient-mode with HTTPS requests.

If I make HTTPS request, it's error.
If I make HTTP request, it's OK.

### What actually happened?

When I run HTTPS request in a buffer with 'restclient-mode', I get error:

```
Debugger entered--Lisp error: (error "Defining as dynamic an already lexical var")
  internal--define-uninitialized-variable(gnutls-verify-error "If non-nil, this should be t or a list of checks p...")
  custom-declare-variable(gnutls-verify-error (funcall #'#f(compiled-function () #<bytecode 0x1dc00016fe914>)) "If non-nil, this should be t or a list of checks p..." :version "24.4" :type (choice (const t) (repeat :tag "List of hostname regexps with flags for each" (list (choice :tag "Hostname" (const ".*" :tag "Any hostname") regexp) (set (const :trustfiles) (const :hostname))))))
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310\311\312\313\314&\11\210\315\316\317\320\321DD\322\323\324%\210\315\325\317\320\326DD\327\307\330\323\331&\7\210\315\332..." [require cl-lib puny custom-declare-group gnutls nil "Emacs interface to the GnuTLS library." :version "24.1" :prefix "gnutls-" :group comm custom-declare-variable gnutls-algorithm-priority funcall function #f(compiled-function () #<bytecode 0x1dc00016fe914>) "If non-nil, this should be a TLS priority string.\n..." :type (choice (const nil) string) gnutls-verify-error #f(compiled-function () #<bytecode 0x1dc00016fe914>) "If non-nil, this should be t or a list of checks p..." "24.4" (choice (const t) (repeat :tag "List of hostname regexps with flags for each" (list (choice :tag "Hostname" (const ".*" :tag "Any hostname") regexp) (set (const :trustfiles) (const :hostname))))) gnutls-trustfiles #f(compiled-function () #<bytecode 0xffa67b7ddbb1215>) "List of CA bundle location filenames or a function..." (choice (function :tag "Function to produce list of bundle filenames") (repeat (file :tag "Bundle filename"))) gnutls-min-prime-bits #f(compiled-function () #<bytecode 0x1dc00016fe914>) "Minimum number of prime bits accepted by GnuTLS fo..." (choice (const :tag "Use default value" nil) (integer :tag "Number of bits" 2048)) "27.1" gnutls-crlfiles #f(compiled-function () #<bytecode 0x123f8a533d8243d7>) "List of CRL file paths or a function returning sai..." (choice (function :tag "Function to produce list of CRL filenames") (repeat (file :tag "CRL filename")))] 10)
  open-gnutls-stream("duckduckgo.com" #<buffer  *url-http-temp*> "duckduckgo.com" 443 (:type tls :nowait (:nowait t)))
  network-stream-open-tls("duckduckgo.com" #<buffer  *url-http-temp*> "duckduckgo.com" 443 (:type tls :nowait (:nowait t)))
  open-network-stream("duckduckgo.com" #<buffer  *url-http-temp*> "duckduckgo.com" 443 :type tls :nowait (:nowait t))
  url-open-stream("duckduckgo.com" #<buffer  *url-http-temp*> "duckduckgo.com" 443 tls)
  url-http-find-free-connection("duckduckgo.com" 443 tls)
  url-http(#s(url :type "https" :user nil :password nil :host "duckduckgo.com" :portspec nil :filename "" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous t) restclient-http-handle-response (nil "GET" "https://duckduckgo.com" "*HTTP Response*" nil t) nil tls)
  url-https(#s(url :type "https" :user nil :password nil :host "duckduckgo.com" :portspec nil :filename "" :target nil :attributes nil :fullness t :silent nil :use-cookies t :asynchronous t) restclient-http-handle-response (nil "GET" "https://duckduckgo.com" "*HTTP Response*" nil t))
  url-retrieve-internal("https://duckduckgo.com" restclient-http-handle-response (nil "GET" "https://duckduckgo.com" "*HTTP Response*" nil t) nil nil)
  url-retrieve("https://duckduckgo.com" restclient-http-handle-response ("GET" "https://duckduckgo.com" "*HTTP Response*" nil t) nil nil)
  #f(compiled-function (method url headers entity &rest handle-args) #<bytecode 0x12f439e83e5eb22a>)("GET" "https://duckduckgo.com" nil "" nil t)
  apply(#f(compiled-function (method url headers entity &rest handle-args) #<bytecode 0x12f439e83e5eb22a>) ("GET" "https://duckduckgo.com" nil "" nil t))
  (let (gnutls-verify-error tls-checktrust) (apply fn args))
  +rest--permit-self-signed-ssl-a(#f(compiled-function (method url headers entity &rest handle-args) #<bytecode 0x12f439e83e5eb22a>) "GET" "https://duckduckgo.com" nil "" nil t)
  apply(+rest--permit-self-signed-ssl-a #f(compiled-function (method url headers entity &rest handle-args) #<bytecode 0x12f439e83e5eb22a>) ("GET" "https://duckduckgo.com" nil "" nil t))
  restclient-http-do("GET" "https://duckduckgo.com" nil "" nil t)
  apply(restclient-http-do "GET" "https://duckduckgo.com" nil "" (nil t))
  restclient-http-parse-current-and-do(restclient-http-do nil t)
  restclient-http-send-current(nil t)
  restclient-http-send-current-stay-in-window()
  (progn (restclient-http-send-current-stay-in-window))
  (if (+rest-request-at-point-p) (progn (restclient-http-send-current-stay-in-window)))
  +rest/dwim-at-point()
  funcall-interactively(+rest/dwim-at-point)
  call-interactively(+rest/dwim-at-point nil nil)
  command-execute(+rest/dwim-at-point)
```

### Describe your attempts to resolve the issue

I "resolved" the problem:

1. Removed "rest" module from init.el.
2. Wrote next packages in packages.el:
`(package! restclient)
(package! company-restclient)
(package! know-your-http-well)
(package! ob-restclient)
`
3. Make doom sync.

### Steps to reproduce

1. Install Doom and uncomment "rest" module in init.el.
2. Open a new buffer and make 'M-x restclient-mode'.
3. Write any HTTPS request. For example: 'GET https://duckduckgo.com'.
4. Run the request by pressing RET.
5. Get message: "Defining as dynamic an already lexical var".
6. Look at '*Messages*' buffer:
> HTTP GET https://duckduckgo.com Headers:[nil] Body:[]
> Contacting host: duckduckgo.com:443
> custom-declare-variable: Defining as dynamic an already lexical var

### System Information

https://pastebin.com/Wutda00S

### PR DESCRIPTION
**Pull request by tohuuquan**
Hi, I encounter the same problem as mentioned in issue #6073 . I've tried to fix it and it works well on my machine, so I would like to contribute it back.

Fixes #6073

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] Any relevant issues or PRs have been linked to.

### CODE REVIEW

**Comment by elken** [comment]
I can't replicate the issue in question on 28.1. Is this a 29-only bug?

**Comment by tohuuquan** [comment]
I didn't notice that Emacs version of the issue in question is 29; I haven't tried version 29 yet.
For me, I'm running version 28.1 on MacOS and Linux; both are having the problem.

System information:
```
generated  Jul 01, 2022 13:28:06
system     MacOS 12.4 Darwin 21.5.0 arm64
emacs      28.1 ~/.config/emacs/ -> ~/.config/emacs/
doom       3.0.0-dev HEAD -> master c2f8476c 2022-06-29 18:12:43 +0200
	   ~/.doom.d/ -> ~/.doom.d/
shell      /opt/homebrew/bin/fish
features   ACL GIF GLIB GMP GNUTLS IMAGEMAGICK JPEG JSON LCMS2 LIBXML2 MODULES
	   NATIVE_COMP NOTIFY KQUEUE NS PDUMPER PNG RSVG THREADS TIFF
	   TOOLKIT_SCROLL_BARS XIM XWIDGETS ZLIB
traits     batch server-running envvar-file custom-file
modules    :completion (vertico +icons) company :ui modeline treemacs vc-gutter
	   nav-flash ophints (popup +defaults) unicode (emoji +unicode) :editor
	   file-templates snippets multiple-cursors :emacs (dired +icons)
	   ibuffer undo :term eshell vterm :checkers syntax :tools magit lsp
	   make lookup :lang (org +roam2) emacs-lisp clojure (ruby +rbenv
	   +rails) (go +lsp) (sh +fish) yaml json (rest +jq) :config default
	   :email mu4e
packages   (mu4e-alert :disable t) (doom-snippets :disable t)
```

**Comment by hlissner** [comment]
Sorry for the late response. I've converted this to a draft because I agree the issue should be addressed, but a better solution is needed, as this issue will affect any package that lexically binds a variable that is defined (and/or made buffer-local) within that scope. In fact, I'm inclined to say this is an upstream issue. 

In any case, this needs more investigation, but I'm a little swamped at the moment. I'll revisit this as soon as I can.

**Comment by fosskers** [comment]
It may be 29-only, as I just hit the original issue.

**Pull request closed without merging**
