### PR TITLE
fix(popup): fix finding of major side window

### PR DESCRIPTION
**Pull request by real-or-random**
Fix: #7647
Amend: #7598

---

- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] Any relevant issues or PRs have been linked to.

Yes, the logic in my previous PR #7598 was a bit too simplistic. This PR should make more sense, and I tested that it resolves the specific problem that @45mm reported in #7647.

@45mm @vherrmann Can you check if this commit resolves the issues?

### CODE REVIEW

**Comment by real-or-random** [comment]
> It doesn't fix my problems but it seems like my problems weren't caused by your previous pr.

Ok, makes sense. (And indeed, your comment in #7647 that popups are entirely broken also sounded to me a bit as if it's unrelated.)

**Comment by 45mm** [comment]
> Can you check if this commit resolves the issues?

Yeah, this fixes the issue for me. Thanks!

**Comment by 45mm** [comment]
@hlissner I guess this is ready to merge, pending your approval...

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
LGTM. Thanks for your help!

**Pull request merged**
