### PR TITLE
[docs]docs(migrate):, docs(contributing):, docs(index):: Update references to hlissner/doomemacs and hlissner/doom-emacs to doomemacs/doomemacs

### PR DESCRIPTION
**Pull request by kjharcombe**
-----
- [x ] I searched the issue tracker and this hasn't been PRed before.
- [ x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [x ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).

### CODE REVIEW

**Comment by gagbo** [comment]
Pretty sure that's not what you wanted

**Comment by kjharcombe** [comment]
> Pretty sure that's not what you wanted

I'm not quite sure I understand what you are saying.

**Comment by hlissner** [comment]
Thank you for the PR, but I must refuse it. I'm not currently accepting PRs to `docs/*.org`, even on the rewrite-docs branch, because I haven't pushed my rewrites of them yet. 

As a side note: a lot of extra git history has snuck into this PR and the commit message doesn't conform to our [git conventions](https://discourse.doomemacs.org/t/git-conventions/2407).

All that said, thank you for bringing them to my attention, I'll be sure to correct them before I pushed the new files in `doc/*.org`.

**Comment by kjharcombe** [comment]
@hlissner, thank you for letting me know. If you do require any help with documentation in the future, let me know as I don't mind contributing to Doom Emacs

**Pull request closed without merging**
