### PR TITLE
tweak(magit): enable gitflow using a flag

### PR DESCRIPTION
**Pull request by Dav1d23**
There are a couple of reasons why we want to hide gitflow behind a feature flag:
- it is not used by everyone, and
- the default keybinding (C-f) is one of Emacs's standard ones.

As we already have `forge` as a flag, I think it makes sense to also have `gitflow` not enabled by default.

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [ ] My changes are visual; I've included before and after screenshots.
- [ ] I am blindly checking these off.
- [x] Any relevant issues or PRs have been linked to.
- [ ] This a draft PR; I need more time to finish it.

### CODE REVIEW

**Comment by Dav1d23** [comment]
One small note about the `My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.`
It seems that what I'm touching is currently frozen, but as I'm not sure... Here we are.

Sorry about the noise, in case.

**Comment by hlissner** [comment]
> It seems that what I'm touching is currently frozen, but as I'm not sure... Here we are.
> 
> Sorry about the noise, in case.

No worries! That freeze is on hiatus at the moment, because I've been away from the project for two months and currently in catch-up mode. The freeze will be reinstated again soon, but I'm accepting PRs to modules in the meantime.

> it is not used by everyone, ...

I already have plans to remove the gitflow plugin altogether because of this and because the configuration for it is trivial, so I think I will push up those plans rather than accept this PR. That said, I'll leave this open until this is done. Thanks for bringing it to my attention, in any case!

**Comment by Dav1d23** [comment]
Thanks for taking care of this.
I'll maintain my fork until this is done, sorry about the bumps to this PR that seems to happen automatically whenever I sync my repo with the official one 😓

**Comment by hlissner** [comment]
And done. Thanks again!

> sorry about the bumps

No worries!

**Pull request closed without merging**
