### PR TITLE
fix(ansible): update emacs-ansible to fetch from the new repo on gitlab

### PR DESCRIPTION
**Pull request by MuhmdRaouf**
As per emacs-ansible old repo's README https://github.com/k1LoW/emacs-ansible the package moved into gitlab
so I just updated `:pin` in `packages.el` to read from the new source https://gitlab.com/emacs-ansible/emacs-ansible

Before:
Screenshot 2024-07-09 at 12 57 21 AM

After:
Screenshot 2024-07-09 at 12 57 40 AM

-----
- [x] I searched the issue tracker and this hasn't been PRed before.
- [x] My changes are not on [the do-not-PR list](https://doomemacs.org/d/do-not-pr) for this project.
- [ ] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [x] My changes are visual; I've included before and after screenshots.

### CODE REVIEW

**Comment by hlissner** [comment]
This should not be necessary, because the MELPA recipe already points to gitlab: https://github.com/melpa/melpa/blob/master/recipes/ansible

**Comment by MuhmdRaouf** [comment]
then how about the error in the first screenshot, how can I fix that?

```
> Cloning emacs-ansible...
✓ (223/335) emacs-ansible: eebb2fb -> b4dca00 [1 commit(s)]
  ERROR: Couldn't collect commit list because: fatal: bad object b4dca00f89334392d770a7a67fffc935ec7354aa
```

I am new to emacs and doom emacs, so maybe there was an easier way and I don't know it.

Thanks in advance.

**Comment by hlissner** [comment]
Just updating the `:pin` should be enough. Try this:

```elisp
;;; add to $DOOMDIR/packages.el
(package! ansible :recipe (:nonrecursive t) :pin "eebb2fb49d3c0a0586d1e4ead9ba618c7d003cae")
```

Then run `doom sync`.

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Thanks for your help!

**Pull request merged**
