### PR TITLE
Update download command in getting_started.org

### PR DESCRIPTION
**Pull request by 4goodapp**
Added --depth 1 in the command to download git.

### CODE REVIEW

**Comment by iyefrat** [comment]
Hey, Doom currently isn't accepting changes to docs files under `docs`, see the [do-not-pr list](https://discourse.doomemacs.org/t/do-not-pr/2406). Also, it has switched to `master` as the main branch, in case you aren't aware, so pull requests should go to there.

**Comment by 4goodapp** [comment]
> Hey, Doom currently isn't accepting changes to docs files under `docs`, see the [do-not-pr list](https://discourse.doomemacs.org/t/do-not-pr/2406). Also, it has switched to `master` as the main branch, in case you aren't aware, so pull requests should go to there.

it's a small change but an important one I think, so I think it's worth adding it cause without the `--depth 1` option, cloning the repose download 116136 files - 40MB+ on your system versus 1148 files - 7MB with that option as of this writing.

**Comment by hlissner** [comment]
Everything in docs/*.org will be rewritten. This includes the chemacs instructions. Not to mention, Doom can replace Chemacs once v3 is out, so this change would not survive long enough to warrant the addition. Thanks for bringing it to our attention, in any case.

**Comment by 4goodapp** [comment]
> Not to mention, Doom can replace Chemacs once v3 is out

That's a good news.

**Pull request closed without merging**
