### PR TITLE
Add julia +snail 

### PR DESCRIPTION
**Pull request by Emiller88**
[Julia Module Refactor](https://discourse.doomemacs.org/t/julia-module-refactor/2797)

-----
- [X] I searched the issue tracker and this hasn't been PRed before.
- [X] My commits conform to [the git conventions](https://doomemacs.org/d/git-conventions).
- [X] I am blindly checking these off.
- [X] This a draft PR; I need more time to finish it.

### CODE REVIEW

**Comment by jeetelongname** [comment]
Just a heads up, until rewrite docs is merged, doc PRs should go into another PR targeting `rewrite-docs` 

also CC @tecosaur

**Comment by Emiller88** [comment]
> Just a heads up, until rewrite docs is merged, doc PRs should go into another PR targeting `rewrite-docs`
> 
> also CC @tecosaur

Appreciate it, I didn't think it was adding much, so if you want me to take them out I certainly will, and we'll make an issue to add the documentation for it.

**Comment by jeetelongname** [comment]
Its not about size but merge conflicts, by freezing docs in `master` it can eliminate a lot of that. 

plus the format is different in subtle ways meaning it makes sense to send doc updates to `rewrite-docs` instead. In any case this can come later, just mentioning it now for posterity

**Comment by Emiller88** [comment]
Sounds good, thanks for the explanation! I removed them and made [an issue ](https://github.com/doomemacs/doomemacs/issues/6594) to go back and add some more docs on what it's doing once we iron this out.

**Comment by iyefrat** [comment]
By the way, now that `rewrite-docs` is merged you can add the docs changes back in

**Review by hlissner — CHANGES_REQUESTED** [review]
What is the state of this PR? At a glance, it seems merge-ready; if you think it's in good enough shape (whether or not it's done), I'd be happy to merge it now and work on it from there.

**Comment by Emiller88** [comment]
Merge away! I've been using it with no major issues, so I'd like to see others opinions and iteration on it(@tecosaur)

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Perfect! Thanks again for your help!

**Pull request merged**
